# Generated by Django 5.0.6 on 2024-07-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_genre_alter_user_books_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='death',
        ),
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
